/*
CREATED BY SAMIRA ALVES LUCIO DIAS
DATE: 24/09/2020
GOAL: Report developed to obtain the total quantity by hospital bed status,
hospitalization unit and period*/

SELECT ATENDIME.CD_PRESTADOR
      ,PRESTADOR.NM_PRESTADOR
      ,COUNT (*) AS TOTAL_DE_ATENDIMENTO
FROM ATENDIME ATENDIME 
INNER JOIN PRESTADOR PRESTADOR
ON ATENDIME.CD_PRESTADOR = PRESTADOR.CD_PRESTADOR -- UNIFICADOR DE TABELAS 
WHERE ATENDIME.DT_ATENDIMENTO = TO_DATE('2020-05-28','YYYY-MM-DD')
GROUP BY ATENDIME.CD_PRESTADOR, PRESTADOR.NM_PRESTADOR
ORDER BY ATENDIME.CD_PRESTADOR DESC;

SELECT UNID_INT.DS_UNID_INT
       ,DECODE (LEITO.TP_OCUPACAO, 'I','LEITO INFECTADO'
                                 ,'M','LEITO EM MANUTENÇÃO'
                                 ,'T','INTERDIÇÃO TEMPORÁRIA') TP_ocupacao
      ,COUNT(*) AS TOTAL_DE_TRANSFERENCIAS
FROM LEITO LEITO
INNER JOIN MOV_INT MOV_INT
  ON MOV_INT.CD_LEITO = LEITO.CD_LEITO
INNER JOIN UNID_INT UNID_INT
  ON UNID_INT.CD_UNID_INT = LEITO.CD_UNID_INT
WHERE LEITO.TP_OCUPACAO IN ('I','M','T')
AND MOV_INT.HR_LIB_MOV IS NOT NULL
AND MOV_INT.DT_LIB_MOV BETWEEN '01/01/2020' AND '24/09/2020'
GROUP BY UNID_INT.DS_UNID_INT, TP_OCUPACAO
ORDER BY UNID_INT.DS_UNID_INT;
