/*
CREATED BY SAMIRA ALVES LUCIO DIAS
DATE: 24/09/2020
GOAL: Report developed to obtain quantity by hospital bed status
,hospitalization unit and period
*/

SELECT 
  LEITO.CD_LEITO,
  LEITO.DS_LEITO,
  LEITO.DS_RESUMO,
  LEITO.DS_ENFERMARIA,
  LEITO.CD_UNID_INT,
  UNID_INT.DS_UNID_INT,
  LEITO.CD_TIP_ACOM,
  DECODE (LEITO.TP_OCUPACAO,'V','LEITO VAGO'
                                 ,'O','OCUPADO'
                                 ,'I','LEITO INFECTADO'
                                 ,'M','LEITO EM MANUTENÇÃO'
                                 ,'R','LEITO EM RESERVA'
                                 ,'A','OCUPADO POR ACOMPANHANTE'
                                 ,'L','LEITO EM LIMPEZA'
                                 ,'T','INTERDIÇÃO TEMPORÁRIA') ocupacao,
  LEITO.TP_SEXO,
  to_char(MOV_INT.DT_LIB_MOV,'DD/MM/YYYY') "DIA",
  SUBSTR(TO_CHAR(MOV_INT.HR_LIB_MOV),10,20) AS HORARIO
FROM DBAMV.LEITO LEITO
INNER JOIN UNID_INT UNID_INT
  ON UNID_INT.CD_UNID_INT = LEITO.CD_UNID_INT
INNER JOIN MOV_INT MOV_INT
  ON MOV_INT.CD_LEITO = LEITO.CD_LEITO
WHERE LEITO.TP_OCUPACAO <> 'O'
AND LEITO.TP_SITUACAO    = 'A'
AND LEITO.CD_UNID_INT   IN
  (SELECT UNID_INT.CD_UNID_INT
      
  FROM DBAMV.UNID_INT
  WHERE UNID_INT.CD_SETOR IN
    (SELECT SETOR.CD_SETOR FROM DBAMV.SETOR WHERE SETOR.CD_MULTI_EMPRESA = '3'
    )
  )
AND MOV_INT.HR_LIB_MOV IS NOT NULL
AND LEITO.TP_OCUPACAO IN ('I','M','T')
--AND TO_CHAR(MOV_INT.DT_LIB_MOV,'DD/MM/YYYY' ) = '21/09/2020'
AND TO_CHAR(MOV_INT.DT_LIB_MOV,'DD/MM/YYYY' ) BETWEEN '01/09/2020' AND '23/09/2020'
ORDER BY MOV_INT.HR_LIB_MOV DESC
        ,MOV_INT.DT_LIB_MOV
        ,UNID_INT.DS_UNID_INT;


